enable: true

api-key: 'ENTER YOUR vpnapi.io API KEY'

block-vpn: true
block-proxy: false
block-tor: false
block-relay: false

enable-country-whitelist: false
whitelisted-countries:
  - 'PL'

enable-country-blacklist: false
blacklisted-countries:
  - 'RU'

always-allowed-ips:
  - '127.0.0.1'

messages:
  status-enabled: '&7AntiVPN is &aenabled&7.'
  status-disabled: '&7AntiVPN is &cdisabled&7.'
  enabled: '&7AntiVPN has been &aenabled&7.'
  disabled: '&7AntiVPN has been &cdisabled&7.'
  connection-blocked: '&cUsing a VPN is not allowed on this server.'
  reloaded: '&7The AntiVPN configuration has been reloaded.'
  exempt-unknown-action: '&cYou need to specify whether you want to add or remove and exempt.'
  exempt-add-unknown-ip: '&cYou need to specify the IP you want to add exempt for.'
  exempt-remove-unknown-ip: '&cYou need to specify the IP you want to remove exempt for.'
  exempt-added: '&7Connections from &6%s &7are now always allowed.'
  exempt-removed: '7Connections from &6%s &7are no longer always allowed.'
