enable-protection: true

api-key: 'ENTER YOUR vpnapi.io API KEY'

block-vpns: true
block-proxies: false
block-tor-nodes: false
block-relays: false

enable-country-whitelist: false
whitelisted-countries:
  - 'PL'

enable-country-blacklist: false
blacklisted-countries:
  - 'RU'

exempted-ips:
  - '127.0.0.1'

messages:
  connection-blocked: '&cUsing a VPN is not allowed on this server.'
  unknown-command: '&cUnknown command. Type /antivpn help to view all AntiVPN commands.'
  status-enabled: '&7AntiVPN is &aenabled&7.'
  status-disabled: '&7AntiVPN is &cdisabled&7.'
  enabled: '&7AntiVPN has been &aenabled&7.'
  disabled: '&7AntiVPN has been &cdisabled&7.'
  exempt-unknown-action: '&cYou need to specify whether you want to add or remove and exempt.'
  exempt-add-unknown-ip: '&cYou need to specify the IP you want to add exempt for.'
  exempt-added: '&7Connections from &6%s &7are now exempting AntiVPN.'
  exempt-remove-unknown-ip: '&cYou need to specify the IP you want to remove exempt for.'
  exempt-removed: '&7Connections from &6%s &7are no longer exempting AntiVPN.'
  reloaded: '&7The AntiVPN configuration has been reloaded.'
  