enable: true

api-key: 'ENTER YOUR vpnapi.io API KEY'

block-vpn: true
block-proxy: false
block-tor: false
block-relay: false

enable-country-whitelist: false
whitelisted-countries:
  - 'PL'

enable-country-blacklist: false
blacklisted-countries:
  - 'RU'

always-allowed-ips:
  - '127.0.0.1'

messages:
  enabled: '&7AntiVPN has been &aenabled&7.'
  disabled: '&7AntiVPN has been &cdisabled&7.'
  kicked: '&cUsing a VPN is not allowed on this server.'
  reloaded: '&7The AntiVPN configuration has been reloaded.'
  always-allowed-ip-added: '&7Connections from &6%s &7are now always allowed.'
  always-allowed-ip-removed: '7Connections from &6%s &7are no longer always allowed.'
